### ISSUE TITLE
Links in Example MkDocs Basic not working

### ISSUE THREAD

**Issue by harleyndavis** [readthedocs-examples/example-mkdocs-basic#11]
On this page: https://github.com/readthedocs-examples/example-mkdocs-basic/blob/main/docs/index.md

Links to "usage" and "install" do not work, which look like they should both be referencing the file at:
https://github.com/readthedocs-examples/example-mkdocs-basic/blob/main/docs/usage.md

Also on that usage.md page, a linke for "lumache.InvalidKindError" doesn't work.

Looks like it is referencing the file at:
https://github.com/readthedocs-examples/example-mkdocs-basic/blob/main/api.md

**Comment by stsewd** [comment]
Hi, the links work on the rendered version https://example-mkdocs-basic.readthedocs.io/en/latest/, the docs use mkdocs, they aren't meant to be rendered on GH.

**Comment by harleyndavis** [comment]
Oh sorry about that then. I guess I was confused I was getting there from https://example-mkdocs-basic.readthedocs.io/en/latest/, and I thought I was going to be looking at an example of documentation produced from that, but now realized I misread. 

Thanks for the reply.
