### ISSUE TITLE
.readthedocs.yaml not up-2-date?

### ISSUE THREAD

**Issue by buhtz** [readthedocs-examples/example-mkdocs-basic#12]
It might be that your example project is not up-2-date anymore.

This in the docu looks more fresh.
https://docs.readthedocs.io/en/stable/config-file/v2.html#configuration-file-reference

**Comment by humitos** [comment]
Thanks for the pointer. I updated it in https://github.com/readthedocs-examples/example-mkdocs-basic/commit/6a8d17d90642552ebd8960672ae1785f73811b07
